OUTPUT_DIR: "./exp_cuhk"
INPUT:
  DATASET: "CUHK-SYSU"
  DATA_ROOT: "/data/aosun/Desktop/code/git-repo/PS-ARM/data/CUHK_SYSU"
  BATCH_SIZE_TRAIN: 3
SOLVER:
  MAX_EPOCHS: 12
  BASE_LR: 0.003
  ATTENTION_YPE: SiMAM
MODEL:
  LOSS:
    TYPE: 'OIM'
    LUT_SIZE: 5532
    CQ_SIZE: 5000
