OUTPUT_DIR: "./logs/prw_coat"
INPUT:
  DATASET: "PRW"
  DATA_ROOT: "/data/aosun/Desktop/code/git-repo/PS-ARM/data/PRW"
  BATCH_SIZE_TRAIN: 3
SOLVER:
  MAX_EPOCHS: 12
  BASE_LR: 0.003
  ATTENTION_YPE: SiMAM
MODEL:
  LOSS:
    TYPE: 'OIM'
    LUT_SIZE: 482
    CQ_SIZE: 500
DISP_PERIOD: 100
