OUTPUT_DIR: "./exp_cuhk"
INPUT:
  DATASET: "CUHK-SYSU"
  DATA_ROOT: "/data1/mustansar/dataset/CUHK-SYSU"
  BATCH_SIZE_TRAIN: 3
SOLVER:
  MAX_EPOCHS: 13
  BASE_LR: 0.003
MODEL:
  LOSS:
    LUT_SIZE: 5532
    CQ_SIZE: 5000
