OUTPUT_DIR: "./logs/prw_coat"
INPUT:
  DATASET: "PRW"
  DATA_ROOT: "/home/huaqiang/aosun/git-repo/PS-ARM_local/PS-ARM/data/PRW-v16.04.20"
  BATCH_SIZE_TRAIN: 3
SOLVER:
  MAX_EPOCHS: 12
  BASE_LR: 0.003
MODEL:
  LOSS:
    LUT_SIZE: 482
    CQ_SIZE: 500
DISP_PERIOD: 100
