OUTPUT_DIR: "./logs/prw_coat_mini"
INPUT:
  DATASET: "PRW"
  DATA_ROOT: "/data/aosun/Desktop/code/git-repo/PS-ARM/data/PRW_MINI/PRW_SEG_VOC_MIX"
  BATCH_SIZE_TRAIN: 3
SOLVER:
  MAX_EPOCHS: 12
  BASE_LR: 0.003
MODEL:
  LOSS:
    LUT_SIZE: 482
    CQ_SIZE: 500
DISP_PERIOD: 100
